### ISSUE TITLE
How to build or compile against?

### ISSUE THREAD

**Issue by salk31** [nkolban/jpigpio#6]
Hi,

Sorry if I've missed something but I'm not sure how to get the required jar.

I tried make but it seems to need a file in /mnt/share/opt/lib/Pigpio.jar

Thanks

Sam

**Comment by sovcik** [comment]
jar & javadoc available in https://github.com/sovcik/jpigpio/releases/tag/v0.5

**Comment by salk31** [comment]
Thanks! Sorry I didn't see that.
